spring:
  application:
    name: demo
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:integrations
    driverClassName: org.h2.Driver
    username: integrations
    password: sekret

# Tomcat
server:
  port: 1235
  tomcat:
    mbeanregistry:
      enabled: true

logging:
  config: classpath:logback-dev.xml

# Actuator
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    propagation:
      type: b3
  endpoints:
    web:
      exposure:
        include: '*'
